### ISSUE TITLE
Change LastUpdate's data type

### ISSUE THREAD

**Issue by Eagle3386** [Eagle3386/aya-platform#10]
Much like #9, `aya_events.LastUpdate` must be changed to `timestamp` type for consistency reasons, too.

Please use the following SQL query and close the issue to notify me afterwards:
```sql
ALTER TABLE aya_events CHANGE LastUpdate
LastUpdate TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
```

**Comment by Eagle3386** [comment]
@ToxSox did you implement the fix in production environment?

**Comment by ToxSox** [comment]
done
