### ISSUE TITLE
Handynummervalidierung mit niederländischer Telefonnummer

### ISSUE THREAD

**Issue by ToxSox** [Eagle3386/aya-platform#11]
Teilnehmer aus den Niederlanden haben Telefonnummer mit der Syntax:

+31 1 11111111

Dies sieht unser System aber als ungültig an. Ich glaube es müsste an der Länge liegen, also das die zu kurz sind.

**Comment by Eagle3386** [comment]
Validation is done in phpBB, not within AYA platform. Please modify regex there.
