### ISSUE TITLE
Changedate on vehicles to control components

### ISSUE THREAD

**Issue by ToxSox** [Eagle3386/aya-platform#8]
The install judges needs a changedate field on the vehicle entity. Then the judges can check die value of the components and write it with a checkdate down. If a user change his car, the checkdate is before the chancedate and the judge know, that he has to check the values before the next event.

In the first step it is enough that the judges see the changedate and write the checkdate on the installflaws. Because we want to use that on the first event. In the secound step it was nice, to have the checkdate on the database and a display, where the check/changedate is invalid.

**Comment by Eagle3386** [comment]
Needed SQL:
```sql
ALTER TABLE `aya_vehicles`
ADD `LastFlawUpdate` TIMESTAMP NULL DEFAULT NULL
AFTER `InstallFlaws`;
```

**Comment by Eagle3386** [comment]
Implemented, please test.

**Comment by ToxSox** [comment]
I dont see any code changes.

**Comment by Eagle3386** [comment]
Test in test environment.. 😉

**Comment by ToxSox** [comment]
Ok, something went wrong. I want a datefield, which gets an update, if the participant change the components. And this datefield should be only visible, not changeable, on the judge view.

The secound thing is, that the judge controll the values of the installed components. Than the judge write in a field, that the check is ok for value XX€ and the date of the check. So the next judge can see, if the participant change a component and the judge have to check the values another time.

**Comment by Eagle3386** [comment]
Thanks for the quick update! :+1:

In addition to my [aforementioned column addition](#issuecomment-380677121), the following column must be added, too:
```sql
ALTER TABLE aya_vehicles ADD LastUpdate DATETIME
ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER Components;
```
Code & UI for components' price data checks will be implemented soon.

**Comment by ToxSox** [comment]
Habe es auf dem Testsystem getestet. Wenn ich nichts an den Mängeln ändere, dann speichert er den Wert nicht. Wenn ich etwas an den Mängeln ändere, dann ändert er das Prüfdatum, speichert bzw. zeigt den eingegeben Wert aber nicht an. Wenn ich das Fahrzeug als Teilnehmer ändere, dann wird auch das Prüfdatum angepasst.

**Comment by Eagle3386** [comment]
Please see my **updated** SQL commands for extended table structure [above](8#issuecomment-381201232) & verify via test environment.

**Comment by ToxSox** [comment]
the sql is updated.

**Comment by Eagle3386** [comment]
Abandoned due to contractor's unwillingness for proper payment for proper development.
