### ISSUE TITLE
Limit Components texts

### ISSUE THREAD

**Issue by Eagle3386** [Eagle3386/aya-platform#9]
Currently, MySQL's `TEXT` type's length is allowed for `aya_vehicles.Components`.
As with any text-like column on the platform, must be limited, too.

Use the following SQL query to fix it:
```sql
ALTER TABLE aya_vehicles CHANGE Components
Components VARCHAR(1000) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL;
```
Close this issue to notify me of your applied change, please.

**Comment by Eagle3386** [comment]
@ToxSox did you implement the fix in production environment?

**Comment by ToxSox** [comment]
done
